apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:latest
          ports:
            - containerPort: 1883 # MQTT default port
            - containerPort: 8083 # WebSocket port
            - containerPort: 18083 # Dashboard port
          env:
            - name: EMQX_NAME
              value: "emqx"
            - name: EMQX_HOST
              value: "0.0.0.0"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  selector:
    app: emqx
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: websocket
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: dashboard
      protocol: TCP
      port: 18083
      targetPort: 18083
  type: LoadBalancer

